name: Update RSS Feed

on:
  schedule:
    - cron: '0 8 * * *' 
  push:
    branches:
      - main 

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 feedgen

    - name: Run the feed generator script
      run: |
        python rss.py

    - name: Commit and push changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add feed.xml
        git commit -m "Automated feed update"
        git push
