name: Update RSS Feed

on:
  
  schedule:
    - cron: '0 10 * * *' 
  pull_request:
  workflow_dispatch:

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 feedgen

    - name: Run the feed generator script
      run: |
        python rss.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add bydleni_brno_aktuality.xml
        git commit -m "Automated RSS update" || echo "No changes to commit"
        git push
